// Code generated by "enumer -type EquityField -trimprefix EquityField"; DO NOT EDIT.

package td

import (
	"fmt"
	"strings"
)

const (
	_EquityFieldName_0      = "SymbolBidPriceAskPriceLastPriceBidSizeAskSizeAskIDBidIDTotalVolumeLastSizeHighPriceLowPriceClosePriceExchangeIDMarginableDescriptionLastIDOpenPriceNetChange52WeekHigh52WeekLowPERatioAnnualDividendAmountDividendYield"
	_EquityFieldLowerName_0 = "symbolbidpriceaskpricelastpricebidsizeasksizeaskidbididtotalvolumelastsizehighpricelowpriceclosepriceexchangeidmarginabledescriptionlastidopenpricenetchange52weekhigh52weeklowperatioannualdividendamountdividendyield"
	_EquityFieldName_1      = "ExchangeNameDividendDateRegularMarketQuoteRegularMarketTradeRegularMarketLastPriceRegularMarketLastSizeRegularMarketNetChangeSecurityStatusMarkPriceQuoteTimeInLongTradeTimeInLongRegularMarketTradeTimeInLongBidTimeAskTimeAskMicIDBidMicIDLastMicIDNetPercentChangeRegularMarketPercentChangeMarkPriceNetChangeMarkPricePercentChangeHardtoBorrowQuantityHardToBorrowRateHardtoBorrowShortablePostMarketNetChangePostMarketPercentChange"
	_EquityFieldLowerName_1 = "exchangenamedividenddateregularmarketquoteregularmarkettraderegularmarketlastpriceregularmarketlastsizeregularmarketnetchangesecuritystatusmarkpricequotetimeinlongtradetimeinlongregularmarkettradetimeinlongbidtimeasktimeaskmicidbidmicidlastmicidnetpercentchangeregularmarketpercentchangemarkpricenetchangemarkpricepercentchangehardtoborrowquantityhardtoborrowratehardtoborrowshortablepostmarketnetchangepostmarketpercentchange"
)

var (
	_EquityFieldIndex_0 = [...]uint8{0, 6, 14, 22, 31, 38, 45, 50, 55, 66, 74, 83, 91, 101, 111, 121, 132, 138, 147, 156, 166, 175, 182, 202, 215}
	_EquityFieldIndex_1 = [...]uint16{0, 12, 24, 42, 60, 82, 103, 125, 139, 148, 163, 178, 206, 213, 220, 228, 236, 245, 261, 287, 305, 327, 347, 363, 375, 384, 403, 426}
)

func (i EquityField) String() string {
	switch {
	case 0 <= i && i <= 23:
		return _EquityFieldName_0[_EquityFieldIndex_0[i]:_EquityFieldIndex_0[i+1]]
	case 25 <= i && i <= 51:
		i -= 25
		return _EquityFieldName_1[_EquityFieldIndex_1[i]:_EquityFieldIndex_1[i+1]]
	default:
		return fmt.Sprintf("EquityField(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EquityFieldNoOp() {
	var x [1]struct{}
	_ = x[EquityFieldSymbol-(0)]
	_ = x[EquityFieldBidPrice-(1)]
	_ = x[EquityFieldAskPrice-(2)]
	_ = x[EquityFieldLastPrice-(3)]
	_ = x[EquityFieldBidSize-(4)]
	_ = x[EquityFieldAskSize-(5)]
	_ = x[EquityFieldAskID-(6)]
	_ = x[EquityFieldBidID-(7)]
	_ = x[EquityFieldTotalVolume-(8)]
	_ = x[EquityFieldLastSize-(9)]
	_ = x[EquityFieldHighPrice-(10)]
	_ = x[EquityFieldLowPrice-(11)]
	_ = x[EquityFieldClosePrice-(12)]
	_ = x[EquityFieldExchangeID-(13)]
	_ = x[EquityFieldMarginable-(14)]
	_ = x[EquityFieldDescription-(15)]
	_ = x[EquityFieldLastID-(16)]
	_ = x[EquityFieldOpenPrice-(17)]
	_ = x[EquityFieldNetChange-(18)]
	_ = x[EquityField52WeekHigh-(19)]
	_ = x[EquityField52WeekLow-(20)]
	_ = x[EquityFieldPERatio-(21)]
	_ = x[EquityFieldAnnualDividendAmount-(22)]
	_ = x[EquityFieldDividendYield-(23)]
	_ = x[EquityFieldExchangeName-(25)]
	_ = x[EquityFieldDividendDate-(26)]
	_ = x[EquityFieldRegularMarketQuote-(27)]
	_ = x[EquityFieldRegularMarketTrade-(28)]
	_ = x[EquityFieldRegularMarketLastPrice-(29)]
	_ = x[EquityFieldRegularMarketLastSize-(30)]
	_ = x[EquityFieldRegularMarketNetChange-(31)]
	_ = x[EquityFieldSecurityStatus-(32)]
	_ = x[EquityFieldMarkPrice-(33)]
	_ = x[EquityFieldQuoteTimeInLong-(34)]
	_ = x[EquityFieldTradeTimeInLong-(35)]
	_ = x[EquityFieldRegularMarketTradeTimeInLong-(36)]
	_ = x[EquityFieldBidTime-(37)]
	_ = x[EquityFieldAskTime-(38)]
	_ = x[EquityFieldAskMicID-(39)]
	_ = x[EquityFieldBidMicID-(40)]
	_ = x[EquityFieldLastMicID-(41)]
	_ = x[EquityFieldNetPercentChange-(42)]
	_ = x[EquityFieldRegularMarketPercentChange-(43)]
	_ = x[EquityFieldMarkPriceNetChange-(44)]
	_ = x[EquityFieldMarkPricePercentChange-(45)]
	_ = x[EquityFieldHardtoBorrowQuantity-(46)]
	_ = x[EquityFieldHardToBorrowRate-(47)]
	_ = x[EquityFieldHardtoBorrow-(48)]
	_ = x[EquityFieldShortable-(49)]
	_ = x[EquityFieldPostMarketNetChange-(50)]
	_ = x[EquityFieldPostMarketPercentChange-(51)]
}

var _EquityFieldValues = []EquityField{EquityFieldSymbol, EquityFieldBidPrice, EquityFieldAskPrice, EquityFieldLastPrice, EquityFieldBidSize, EquityFieldAskSize, EquityFieldAskID, EquityFieldBidID, EquityFieldTotalVolume, EquityFieldLastSize, EquityFieldHighPrice, EquityFieldLowPrice, EquityFieldClosePrice, EquityFieldExchangeID, EquityFieldMarginable, EquityFieldDescription, EquityFieldLastID, EquityFieldOpenPrice, EquityFieldNetChange, EquityField52WeekHigh, EquityField52WeekLow, EquityFieldPERatio, EquityFieldAnnualDividendAmount, EquityFieldDividendYield, EquityFieldExchangeName, EquityFieldDividendDate, EquityFieldRegularMarketQuote, EquityFieldRegularMarketTrade, EquityFieldRegularMarketLastPrice, EquityFieldRegularMarketLastSize, EquityFieldRegularMarketNetChange, EquityFieldSecurityStatus, EquityFieldMarkPrice, EquityFieldQuoteTimeInLong, EquityFieldTradeTimeInLong, EquityFieldRegularMarketTradeTimeInLong, EquityFieldBidTime, EquityFieldAskTime, EquityFieldAskMicID, EquityFieldBidMicID, EquityFieldLastMicID, EquityFieldNetPercentChange, EquityFieldRegularMarketPercentChange, EquityFieldMarkPriceNetChange, EquityFieldMarkPricePercentChange, EquityFieldHardtoBorrowQuantity, EquityFieldHardToBorrowRate, EquityFieldHardtoBorrow, EquityFieldShortable, EquityFieldPostMarketNetChange, EquityFieldPostMarketPercentChange}

var _EquityFieldNameToValueMap = map[string]EquityField{
	_EquityFieldName_0[0:6]:          EquityFieldSymbol,
	_EquityFieldLowerName_0[0:6]:     EquityFieldSymbol,
	_EquityFieldName_0[6:14]:         EquityFieldBidPrice,
	_EquityFieldLowerName_0[6:14]:    EquityFieldBidPrice,
	_EquityFieldName_0[14:22]:        EquityFieldAskPrice,
	_EquityFieldLowerName_0[14:22]:   EquityFieldAskPrice,
	_EquityFieldName_0[22:31]:        EquityFieldLastPrice,
	_EquityFieldLowerName_0[22:31]:   EquityFieldLastPrice,
	_EquityFieldName_0[31:38]:        EquityFieldBidSize,
	_EquityFieldLowerName_0[31:38]:   EquityFieldBidSize,
	_EquityFieldName_0[38:45]:        EquityFieldAskSize,
	_EquityFieldLowerName_0[38:45]:   EquityFieldAskSize,
	_EquityFieldName_0[45:50]:        EquityFieldAskID,
	_EquityFieldLowerName_0[45:50]:   EquityFieldAskID,
	_EquityFieldName_0[50:55]:        EquityFieldBidID,
	_EquityFieldLowerName_0[50:55]:   EquityFieldBidID,
	_EquityFieldName_0[55:66]:        EquityFieldTotalVolume,
	_EquityFieldLowerName_0[55:66]:   EquityFieldTotalVolume,
	_EquityFieldName_0[66:74]:        EquityFieldLastSize,
	_EquityFieldLowerName_0[66:74]:   EquityFieldLastSize,
	_EquityFieldName_0[74:83]:        EquityFieldHighPrice,
	_EquityFieldLowerName_0[74:83]:   EquityFieldHighPrice,
	_EquityFieldName_0[83:91]:        EquityFieldLowPrice,
	_EquityFieldLowerName_0[83:91]:   EquityFieldLowPrice,
	_EquityFieldName_0[91:101]:       EquityFieldClosePrice,
	_EquityFieldLowerName_0[91:101]:  EquityFieldClosePrice,
	_EquityFieldName_0[101:111]:      EquityFieldExchangeID,
	_EquityFieldLowerName_0[101:111]: EquityFieldExchangeID,
	_EquityFieldName_0[111:121]:      EquityFieldMarginable,
	_EquityFieldLowerName_0[111:121]: EquityFieldMarginable,
	_EquityFieldName_0[121:132]:      EquityFieldDescription,
	_EquityFieldLowerName_0[121:132]: EquityFieldDescription,
	_EquityFieldName_0[132:138]:      EquityFieldLastID,
	_EquityFieldLowerName_0[132:138]: EquityFieldLastID,
	_EquityFieldName_0[138:147]:      EquityFieldOpenPrice,
	_EquityFieldLowerName_0[138:147]: EquityFieldOpenPrice,
	_EquityFieldName_0[147:156]:      EquityFieldNetChange,
	_EquityFieldLowerName_0[147:156]: EquityFieldNetChange,
	_EquityFieldName_0[156:166]:      EquityField52WeekHigh,
	_EquityFieldLowerName_0[156:166]: EquityField52WeekHigh,
	_EquityFieldName_0[166:175]:      EquityField52WeekLow,
	_EquityFieldLowerName_0[166:175]: EquityField52WeekLow,
	_EquityFieldName_0[175:182]:      EquityFieldPERatio,
	_EquityFieldLowerName_0[175:182]: EquityFieldPERatio,
	_EquityFieldName_0[182:202]:      EquityFieldAnnualDividendAmount,
	_EquityFieldLowerName_0[182:202]: EquityFieldAnnualDividendAmount,
	_EquityFieldName_0[202:215]:      EquityFieldDividendYield,
	_EquityFieldLowerName_0[202:215]: EquityFieldDividendYield,
	_EquityFieldName_1[0:12]:         EquityFieldExchangeName,
	_EquityFieldLowerName_1[0:12]:    EquityFieldExchangeName,
	_EquityFieldName_1[12:24]:        EquityFieldDividendDate,
	_EquityFieldLowerName_1[12:24]:   EquityFieldDividendDate,
	_EquityFieldName_1[24:42]:        EquityFieldRegularMarketQuote,
	_EquityFieldLowerName_1[24:42]:   EquityFieldRegularMarketQuote,
	_EquityFieldName_1[42:60]:        EquityFieldRegularMarketTrade,
	_EquityFieldLowerName_1[42:60]:   EquityFieldRegularMarketTrade,
	_EquityFieldName_1[60:82]:        EquityFieldRegularMarketLastPrice,
	_EquityFieldLowerName_1[60:82]:   EquityFieldRegularMarketLastPrice,
	_EquityFieldName_1[82:103]:       EquityFieldRegularMarketLastSize,
	_EquityFieldLowerName_1[82:103]:  EquityFieldRegularMarketLastSize,
	_EquityFieldName_1[103:125]:      EquityFieldRegularMarketNetChange,
	_EquityFieldLowerName_1[103:125]: EquityFieldRegularMarketNetChange,
	_EquityFieldName_1[125:139]:      EquityFieldSecurityStatus,
	_EquityFieldLowerName_1[125:139]: EquityFieldSecurityStatus,
	_EquityFieldName_1[139:148]:      EquityFieldMarkPrice,
	_EquityFieldLowerName_1[139:148]: EquityFieldMarkPrice,
	_EquityFieldName_1[148:163]:      EquityFieldQuoteTimeInLong,
	_EquityFieldLowerName_1[148:163]: EquityFieldQuoteTimeInLong,
	_EquityFieldName_1[163:178]:      EquityFieldTradeTimeInLong,
	_EquityFieldLowerName_1[163:178]: EquityFieldTradeTimeInLong,
	_EquityFieldName_1[178:206]:      EquityFieldRegularMarketTradeTimeInLong,
	_EquityFieldLowerName_1[178:206]: EquityFieldRegularMarketTradeTimeInLong,
	_EquityFieldName_1[206:213]:      EquityFieldBidTime,
	_EquityFieldLowerName_1[206:213]: EquityFieldBidTime,
	_EquityFieldName_1[213:220]:      EquityFieldAskTime,
	_EquityFieldLowerName_1[213:220]: EquityFieldAskTime,
	_EquityFieldName_1[220:228]:      EquityFieldAskMicID,
	_EquityFieldLowerName_1[220:228]: EquityFieldAskMicID,
	_EquityFieldName_1[228:236]:      EquityFieldBidMicID,
	_EquityFieldLowerName_1[228:236]: EquityFieldBidMicID,
	_EquityFieldName_1[236:245]:      EquityFieldLastMicID,
	_EquityFieldLowerName_1[236:245]: EquityFieldLastMicID,
	_EquityFieldName_1[245:261]:      EquityFieldNetPercentChange,
	_EquityFieldLowerName_1[245:261]: EquityFieldNetPercentChange,
	_EquityFieldName_1[261:287]:      EquityFieldRegularMarketPercentChange,
	_EquityFieldLowerName_1[261:287]: EquityFieldRegularMarketPercentChange,
	_EquityFieldName_1[287:305]:      EquityFieldMarkPriceNetChange,
	_EquityFieldLowerName_1[287:305]: EquityFieldMarkPriceNetChange,
	_EquityFieldName_1[305:327]:      EquityFieldMarkPricePercentChange,
	_EquityFieldLowerName_1[305:327]: EquityFieldMarkPricePercentChange,
	_EquityFieldName_1[327:347]:      EquityFieldHardtoBorrowQuantity,
	_EquityFieldLowerName_1[327:347]: EquityFieldHardtoBorrowQuantity,
	_EquityFieldName_1[347:363]:      EquityFieldHardToBorrowRate,
	_EquityFieldLowerName_1[347:363]: EquityFieldHardToBorrowRate,
	_EquityFieldName_1[363:375]:      EquityFieldHardtoBorrow,
	_EquityFieldLowerName_1[363:375]: EquityFieldHardtoBorrow,
	_EquityFieldName_1[375:384]:      EquityFieldShortable,
	_EquityFieldLowerName_1[375:384]: EquityFieldShortable,
	_EquityFieldName_1[384:403]:      EquityFieldPostMarketNetChange,
	_EquityFieldLowerName_1[384:403]: EquityFieldPostMarketNetChange,
	_EquityFieldName_1[403:426]:      EquityFieldPostMarketPercentChange,
	_EquityFieldLowerName_1[403:426]: EquityFieldPostMarketPercentChange,
}

var _EquityFieldNames = []string{
	_EquityFieldName_0[0:6],
	_EquityFieldName_0[6:14],
	_EquityFieldName_0[14:22],
	_EquityFieldName_0[22:31],
	_EquityFieldName_0[31:38],
	_EquityFieldName_0[38:45],
	_EquityFieldName_0[45:50],
	_EquityFieldName_0[50:55],
	_EquityFieldName_0[55:66],
	_EquityFieldName_0[66:74],
	_EquityFieldName_0[74:83],
	_EquityFieldName_0[83:91],
	_EquityFieldName_0[91:101],
	_EquityFieldName_0[101:111],
	_EquityFieldName_0[111:121],
	_EquityFieldName_0[121:132],
	_EquityFieldName_0[132:138],
	_EquityFieldName_0[138:147],
	_EquityFieldName_0[147:156],
	_EquityFieldName_0[156:166],
	_EquityFieldName_0[166:175],
	_EquityFieldName_0[175:182],
	_EquityFieldName_0[182:202],
	_EquityFieldName_0[202:215],
	_EquityFieldName_1[0:12],
	_EquityFieldName_1[12:24],
	_EquityFieldName_1[24:42],
	_EquityFieldName_1[42:60],
	_EquityFieldName_1[60:82],
	_EquityFieldName_1[82:103],
	_EquityFieldName_1[103:125],
	_EquityFieldName_1[125:139],
	_EquityFieldName_1[139:148],
	_EquityFieldName_1[148:163],
	_EquityFieldName_1[163:178],
	_EquityFieldName_1[178:206],
	_EquityFieldName_1[206:213],
	_EquityFieldName_1[213:220],
	_EquityFieldName_1[220:228],
	_EquityFieldName_1[228:236],
	_EquityFieldName_1[236:245],
	_EquityFieldName_1[245:261],
	_EquityFieldName_1[261:287],
	_EquityFieldName_1[287:305],
	_EquityFieldName_1[305:327],
	_EquityFieldName_1[327:347],
	_EquityFieldName_1[347:363],
	_EquityFieldName_1[363:375],
	_EquityFieldName_1[375:384],
	_EquityFieldName_1[384:403],
	_EquityFieldName_1[403:426],
}

// EquityFieldString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EquityFieldString(s string) (EquityField, error) {
	if val, ok := _EquityFieldNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EquityFieldNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EquityField values", s)
}

// EquityFieldValues returns all values of the enum
func EquityFieldValues() []EquityField {
	return _EquityFieldValues
}

// EquityFieldStrings returns a slice of all String values of the enum
func EquityFieldStrings() []string {
	strs := make([]string, len(_EquityFieldNames))
	copy(strs, _EquityFieldNames)
	return strs
}

// IsAEquityField returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EquityField) IsAEquityField() bool {
	for _, v := range _EquityFieldValues {
		if i == v {
			return true
		}
	}
	return false
}
