// Code generated by goku; DO NOT EDIT
// Version: 926fb54d00aef6b391828e191e40fbd4b3e71c43
// Command: goku iface fanoutMutex -m fanoutMock -o fanout_mutex_interface.go --private
package td

import (
	"time"
)

// force the underlying to implement the interface
var _ = fanoutMutexInterface(&fanoutMutex{})

type fanoutMutexInterface interface {
	setTimeout(t time.Duration)
	request() *socketReq
	pub(requests []apiResp)
}

// force the mock to implement the interface
var _ = fanoutMutexInterface(fanoutMock{})

type fanoutMock struct {
	setTimeoutFn func(t time.Duration)
	requestFn    func() *socketReq
	pubFn        func(requests []apiResp)
}

func (mockImplementation fanoutMock) setTimeout(t time.Duration) {
	mockImplementation.setTimeoutFn(t)
}

func (mockImplementation fanoutMock) request() *socketReq {
	return mockImplementation.requestFn()
}

func (mockImplementation fanoutMock) pub(requests []apiResp) {
	mockImplementation.pubFn(requests)
}
