// Code generated by "enumer -type FutureOptionField -trimprefix FutureOptionField"; DO NOT EDIT.

package td

import (
	"fmt"
	"strings"
)

const _FutureOptionFieldName = "SymbolBidPriceAskPriceLastPriceBidSizeAskSizeBidIDAskIDTotalVolumeLastSizeQuoteTimeTradeTimeHighPriceLowPriceClosePriceLastIDDescriptionOpenPriceOpenInterestMarkTickTickAmountFutureMultiplierFutureSettlementPriceUnderlyingSymbolStrikePriceFutureExpirationDateExpirationStyleSideStatusExchangeExchangeName"

var _FutureOptionFieldIndex = [...]uint16{0, 6, 14, 22, 31, 38, 45, 50, 55, 66, 74, 83, 92, 101, 109, 119, 125, 136, 145, 157, 161, 165, 175, 191, 212, 228, 239, 259, 274, 278, 284, 292, 304}

const _FutureOptionFieldLowerName = "symbolbidpriceaskpricelastpricebidsizeasksizebididaskidtotalvolumelastsizequotetimetradetimehighpricelowpriceclosepricelastiddescriptionopenpriceopeninterestmarkticktickamountfuturemultiplierfuturesettlementpriceunderlyingsymbolstrikepricefutureexpirationdateexpirationstylesidestatusexchangeexchangename"

func (i FutureOptionField) String() string {
	if i >= FutureOptionField(len(_FutureOptionFieldIndex)-1) {
		return fmt.Sprintf("FutureOptionField(%d)", i)
	}
	return _FutureOptionFieldName[_FutureOptionFieldIndex[i]:_FutureOptionFieldIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FutureOptionFieldNoOp() {
	var x [1]struct{}
	_ = x[FutureOptionFieldSymbol-(0)]
	_ = x[FutureOptionFieldBidPrice-(1)]
	_ = x[FutureOptionFieldAskPrice-(2)]
	_ = x[FutureOptionFieldLastPrice-(3)]
	_ = x[FutureOptionFieldBidSize-(4)]
	_ = x[FutureOptionFieldAskSize-(5)]
	_ = x[FutureOptionFieldBidID-(6)]
	_ = x[FutureOptionFieldAskID-(7)]
	_ = x[FutureOptionFieldTotalVolume-(8)]
	_ = x[FutureOptionFieldLastSize-(9)]
	_ = x[FutureOptionFieldQuoteTime-(10)]
	_ = x[FutureOptionFieldTradeTime-(11)]
	_ = x[FutureOptionFieldHighPrice-(12)]
	_ = x[FutureOptionFieldLowPrice-(13)]
	_ = x[FutureOptionFieldClosePrice-(14)]
	_ = x[FutureOptionFieldLastID-(15)]
	_ = x[FutureOptionFieldDescription-(16)]
	_ = x[FutureOptionFieldOpenPrice-(17)]
	_ = x[FutureOptionFieldOpenInterest-(18)]
	_ = x[FutureOptionFieldMark-(19)]
	_ = x[FutureOptionFieldTick-(20)]
	_ = x[FutureOptionFieldTickAmount-(21)]
	_ = x[FutureOptionFieldFutureMultiplier-(22)]
	_ = x[FutureOptionFieldFutureSettlementPrice-(23)]
	_ = x[FutureOptionFieldUnderlyingSymbol-(24)]
	_ = x[FutureOptionFieldStrikePrice-(25)]
	_ = x[FutureOptionFieldFutureExpirationDate-(26)]
	_ = x[FutureOptionFieldExpirationStyle-(27)]
	_ = x[FutureOptionFieldSide-(28)]
	_ = x[FutureOptionFieldStatus-(29)]
	_ = x[FutureOptionFieldExchange-(30)]
	_ = x[FutureOptionFieldExchangeName-(31)]
}

var _FutureOptionFieldValues = []FutureOptionField{FutureOptionFieldSymbol, FutureOptionFieldBidPrice, FutureOptionFieldAskPrice, FutureOptionFieldLastPrice, FutureOptionFieldBidSize, FutureOptionFieldAskSize, FutureOptionFieldBidID, FutureOptionFieldAskID, FutureOptionFieldTotalVolume, FutureOptionFieldLastSize, FutureOptionFieldQuoteTime, FutureOptionFieldTradeTime, FutureOptionFieldHighPrice, FutureOptionFieldLowPrice, FutureOptionFieldClosePrice, FutureOptionFieldLastID, FutureOptionFieldDescription, FutureOptionFieldOpenPrice, FutureOptionFieldOpenInterest, FutureOptionFieldMark, FutureOptionFieldTick, FutureOptionFieldTickAmount, FutureOptionFieldFutureMultiplier, FutureOptionFieldFutureSettlementPrice, FutureOptionFieldUnderlyingSymbol, FutureOptionFieldStrikePrice, FutureOptionFieldFutureExpirationDate, FutureOptionFieldExpirationStyle, FutureOptionFieldSide, FutureOptionFieldStatus, FutureOptionFieldExchange, FutureOptionFieldExchangeName}

var _FutureOptionFieldNameToValueMap = map[string]FutureOptionField{
	_FutureOptionFieldName[0:6]:          FutureOptionFieldSymbol,
	_FutureOptionFieldLowerName[0:6]:     FutureOptionFieldSymbol,
	_FutureOptionFieldName[6:14]:         FutureOptionFieldBidPrice,
	_FutureOptionFieldLowerName[6:14]:    FutureOptionFieldBidPrice,
	_FutureOptionFieldName[14:22]:        FutureOptionFieldAskPrice,
	_FutureOptionFieldLowerName[14:22]:   FutureOptionFieldAskPrice,
	_FutureOptionFieldName[22:31]:        FutureOptionFieldLastPrice,
	_FutureOptionFieldLowerName[22:31]:   FutureOptionFieldLastPrice,
	_FutureOptionFieldName[31:38]:        FutureOptionFieldBidSize,
	_FutureOptionFieldLowerName[31:38]:   FutureOptionFieldBidSize,
	_FutureOptionFieldName[38:45]:        FutureOptionFieldAskSize,
	_FutureOptionFieldLowerName[38:45]:   FutureOptionFieldAskSize,
	_FutureOptionFieldName[45:50]:        FutureOptionFieldBidID,
	_FutureOptionFieldLowerName[45:50]:   FutureOptionFieldBidID,
	_FutureOptionFieldName[50:55]:        FutureOptionFieldAskID,
	_FutureOptionFieldLowerName[50:55]:   FutureOptionFieldAskID,
	_FutureOptionFieldName[55:66]:        FutureOptionFieldTotalVolume,
	_FutureOptionFieldLowerName[55:66]:   FutureOptionFieldTotalVolume,
	_FutureOptionFieldName[66:74]:        FutureOptionFieldLastSize,
	_FutureOptionFieldLowerName[66:74]:   FutureOptionFieldLastSize,
	_FutureOptionFieldName[74:83]:        FutureOptionFieldQuoteTime,
	_FutureOptionFieldLowerName[74:83]:   FutureOptionFieldQuoteTime,
	_FutureOptionFieldName[83:92]:        FutureOptionFieldTradeTime,
	_FutureOptionFieldLowerName[83:92]:   FutureOptionFieldTradeTime,
	_FutureOptionFieldName[92:101]:       FutureOptionFieldHighPrice,
	_FutureOptionFieldLowerName[92:101]:  FutureOptionFieldHighPrice,
	_FutureOptionFieldName[101:109]:      FutureOptionFieldLowPrice,
	_FutureOptionFieldLowerName[101:109]: FutureOptionFieldLowPrice,
	_FutureOptionFieldName[109:119]:      FutureOptionFieldClosePrice,
	_FutureOptionFieldLowerName[109:119]: FutureOptionFieldClosePrice,
	_FutureOptionFieldName[119:125]:      FutureOptionFieldLastID,
	_FutureOptionFieldLowerName[119:125]: FutureOptionFieldLastID,
	_FutureOptionFieldName[125:136]:      FutureOptionFieldDescription,
	_FutureOptionFieldLowerName[125:136]: FutureOptionFieldDescription,
	_FutureOptionFieldName[136:145]:      FutureOptionFieldOpenPrice,
	_FutureOptionFieldLowerName[136:145]: FutureOptionFieldOpenPrice,
	_FutureOptionFieldName[145:157]:      FutureOptionFieldOpenInterest,
	_FutureOptionFieldLowerName[145:157]: FutureOptionFieldOpenInterest,
	_FutureOptionFieldName[157:161]:      FutureOptionFieldMark,
	_FutureOptionFieldLowerName[157:161]: FutureOptionFieldMark,
	_FutureOptionFieldName[161:165]:      FutureOptionFieldTick,
	_FutureOptionFieldLowerName[161:165]: FutureOptionFieldTick,
	_FutureOptionFieldName[165:175]:      FutureOptionFieldTickAmount,
	_FutureOptionFieldLowerName[165:175]: FutureOptionFieldTickAmount,
	_FutureOptionFieldName[175:191]:      FutureOptionFieldFutureMultiplier,
	_FutureOptionFieldLowerName[175:191]: FutureOptionFieldFutureMultiplier,
	_FutureOptionFieldName[191:212]:      FutureOptionFieldFutureSettlementPrice,
	_FutureOptionFieldLowerName[191:212]: FutureOptionFieldFutureSettlementPrice,
	_FutureOptionFieldName[212:228]:      FutureOptionFieldUnderlyingSymbol,
	_FutureOptionFieldLowerName[212:228]: FutureOptionFieldUnderlyingSymbol,
	_FutureOptionFieldName[228:239]:      FutureOptionFieldStrikePrice,
	_FutureOptionFieldLowerName[228:239]: FutureOptionFieldStrikePrice,
	_FutureOptionFieldName[239:259]:      FutureOptionFieldFutureExpirationDate,
	_FutureOptionFieldLowerName[239:259]: FutureOptionFieldFutureExpirationDate,
	_FutureOptionFieldName[259:274]:      FutureOptionFieldExpirationStyle,
	_FutureOptionFieldLowerName[259:274]: FutureOptionFieldExpirationStyle,
	_FutureOptionFieldName[274:278]:      FutureOptionFieldSide,
	_FutureOptionFieldLowerName[274:278]: FutureOptionFieldSide,
	_FutureOptionFieldName[278:284]:      FutureOptionFieldStatus,
	_FutureOptionFieldLowerName[278:284]: FutureOptionFieldStatus,
	_FutureOptionFieldName[284:292]:      FutureOptionFieldExchange,
	_FutureOptionFieldLowerName[284:292]: FutureOptionFieldExchange,
	_FutureOptionFieldName[292:304]:      FutureOptionFieldExchangeName,
	_FutureOptionFieldLowerName[292:304]: FutureOptionFieldExchangeName,
}

var _FutureOptionFieldNames = []string{
	_FutureOptionFieldName[0:6],
	_FutureOptionFieldName[6:14],
	_FutureOptionFieldName[14:22],
	_FutureOptionFieldName[22:31],
	_FutureOptionFieldName[31:38],
	_FutureOptionFieldName[38:45],
	_FutureOptionFieldName[45:50],
	_FutureOptionFieldName[50:55],
	_FutureOptionFieldName[55:66],
	_FutureOptionFieldName[66:74],
	_FutureOptionFieldName[74:83],
	_FutureOptionFieldName[83:92],
	_FutureOptionFieldName[92:101],
	_FutureOptionFieldName[101:109],
	_FutureOptionFieldName[109:119],
	_FutureOptionFieldName[119:125],
	_FutureOptionFieldName[125:136],
	_FutureOptionFieldName[136:145],
	_FutureOptionFieldName[145:157],
	_FutureOptionFieldName[157:161],
	_FutureOptionFieldName[161:165],
	_FutureOptionFieldName[165:175],
	_FutureOptionFieldName[175:191],
	_FutureOptionFieldName[191:212],
	_FutureOptionFieldName[212:228],
	_FutureOptionFieldName[228:239],
	_FutureOptionFieldName[239:259],
	_FutureOptionFieldName[259:274],
	_FutureOptionFieldName[274:278],
	_FutureOptionFieldName[278:284],
	_FutureOptionFieldName[284:292],
	_FutureOptionFieldName[292:304],
}

// FutureOptionFieldString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FutureOptionFieldString(s string) (FutureOptionField, error) {
	if val, ok := _FutureOptionFieldNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FutureOptionFieldNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FutureOptionField values", s)
}

// FutureOptionFieldValues returns all values of the enum
func FutureOptionFieldValues() []FutureOptionField {
	return _FutureOptionFieldValues
}

// FutureOptionFieldStrings returns a slice of all String values of the enum
func FutureOptionFieldStrings() []string {
	strs := make([]string, len(_FutureOptionFieldNames))
	copy(strs, _FutureOptionFieldNames)
	return strs
}

// IsAFutureOptionField returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FutureOptionField) IsAFutureOptionField() bool {
	for _, v := range _FutureOptionFieldValues {
		if i == v {
			return true
		}
	}
	return false
}
