// Code generated by "enumer -type FutureField -trimprefix FutureField"; DO NOT EDIT.

package td

import (
	"fmt"
	"strings"
)

const _FutureFieldName = "SymbolBidPriceAskPriceLastPriceBidSizeAskSizeBidIDAskIDTotalVolumeLastSizeQuoteTimeTradeTimeHighPriceLowPriceClosePriceExchangeIDDescriptionLastIDOpenPriceNetChangePercentChangeExchangeNameSecurityStatusOpenInterestMarkTickTickAmountProductFuturePriceFmtTradingHoursIsTradableMultiplierIsActiveSettlementPriceActiveSymbolExpirationDateExpirationStyleAskTimeBidTimeQuotedInSessionSettlementDate"

var _FutureFieldIndex = [...]uint16{0, 6, 14, 22, 31, 38, 45, 50, 55, 66, 74, 83, 92, 101, 109, 119, 129, 140, 146, 155, 164, 177, 189, 203, 215, 219, 223, 233, 240, 254, 266, 276, 286, 294, 309, 321, 335, 350, 357, 364, 379, 393}

const _FutureFieldLowerName = "symbolbidpriceaskpricelastpricebidsizeasksizebididaskidtotalvolumelastsizequotetimetradetimehighpricelowpriceclosepriceexchangeiddescriptionlastidopenpricenetchangepercentchangeexchangenamesecuritystatusopeninterestmarkticktickamountproductfuturepricefmttradinghoursistradablemultiplierisactivesettlementpriceactivesymbolexpirationdateexpirationstyleasktimebidtimequotedinsessionsettlementdate"

func (i FutureField) String() string {
	if i >= FutureField(len(_FutureFieldIndex)-1) {
		return fmt.Sprintf("FutureField(%d)", i)
	}
	return _FutureFieldName[_FutureFieldIndex[i]:_FutureFieldIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FutureFieldNoOp() {
	var x [1]struct{}
	_ = x[FutureFieldSymbol-(0)]
	_ = x[FutureFieldBidPrice-(1)]
	_ = x[FutureFieldAskPrice-(2)]
	_ = x[FutureFieldLastPrice-(3)]
	_ = x[FutureFieldBidSize-(4)]
	_ = x[FutureFieldAskSize-(5)]
	_ = x[FutureFieldBidID-(6)]
	_ = x[FutureFieldAskID-(7)]
	_ = x[FutureFieldTotalVolume-(8)]
	_ = x[FutureFieldLastSize-(9)]
	_ = x[FutureFieldQuoteTime-(10)]
	_ = x[FutureFieldTradeTime-(11)]
	_ = x[FutureFieldHighPrice-(12)]
	_ = x[FutureFieldLowPrice-(13)]
	_ = x[FutureFieldClosePrice-(14)]
	_ = x[FutureFieldExchangeID-(15)]
	_ = x[FutureFieldDescription-(16)]
	_ = x[FutureFieldLastID-(17)]
	_ = x[FutureFieldOpenPrice-(18)]
	_ = x[FutureFieldNetChange-(19)]
	_ = x[FutureFieldPercentChange-(20)]
	_ = x[FutureFieldExchangeName-(21)]
	_ = x[FutureFieldSecurityStatus-(22)]
	_ = x[FutureFieldOpenInterest-(23)]
	_ = x[FutureFieldMark-(24)]
	_ = x[FutureFieldTick-(25)]
	_ = x[FutureFieldTickAmount-(26)]
	_ = x[FutureFieldProduct-(27)]
	_ = x[FutureFieldFuturePriceFmt-(28)]
	_ = x[FutureFieldTradingHours-(29)]
	_ = x[FutureFieldIsTradable-(30)]
	_ = x[FutureFieldMultiplier-(31)]
	_ = x[FutureFieldIsActive-(32)]
	_ = x[FutureFieldSettlementPrice-(33)]
	_ = x[FutureFieldActiveSymbol-(34)]
	_ = x[FutureFieldExpirationDate-(35)]
	_ = x[FutureFieldExpirationStyle-(36)]
	_ = x[FutureFieldAskTime-(37)]
	_ = x[FutureFieldBidTime-(38)]
	_ = x[FutureFieldQuotedInSession-(39)]
	_ = x[FutureFieldSettlementDate-(40)]
}

var _FutureFieldValues = []FutureField{FutureFieldSymbol, FutureFieldBidPrice, FutureFieldAskPrice, FutureFieldLastPrice, FutureFieldBidSize, FutureFieldAskSize, FutureFieldBidID, FutureFieldAskID, FutureFieldTotalVolume, FutureFieldLastSize, FutureFieldQuoteTime, FutureFieldTradeTime, FutureFieldHighPrice, FutureFieldLowPrice, FutureFieldClosePrice, FutureFieldExchangeID, FutureFieldDescription, FutureFieldLastID, FutureFieldOpenPrice, FutureFieldNetChange, FutureFieldPercentChange, FutureFieldExchangeName, FutureFieldSecurityStatus, FutureFieldOpenInterest, FutureFieldMark, FutureFieldTick, FutureFieldTickAmount, FutureFieldProduct, FutureFieldFuturePriceFmt, FutureFieldTradingHours, FutureFieldIsTradable, FutureFieldMultiplier, FutureFieldIsActive, FutureFieldSettlementPrice, FutureFieldActiveSymbol, FutureFieldExpirationDate, FutureFieldExpirationStyle, FutureFieldAskTime, FutureFieldBidTime, FutureFieldQuotedInSession, FutureFieldSettlementDate}

var _FutureFieldNameToValueMap = map[string]FutureField{
	_FutureFieldName[0:6]:          FutureFieldSymbol,
	_FutureFieldLowerName[0:6]:     FutureFieldSymbol,
	_FutureFieldName[6:14]:         FutureFieldBidPrice,
	_FutureFieldLowerName[6:14]:    FutureFieldBidPrice,
	_FutureFieldName[14:22]:        FutureFieldAskPrice,
	_FutureFieldLowerName[14:22]:   FutureFieldAskPrice,
	_FutureFieldName[22:31]:        FutureFieldLastPrice,
	_FutureFieldLowerName[22:31]:   FutureFieldLastPrice,
	_FutureFieldName[31:38]:        FutureFieldBidSize,
	_FutureFieldLowerName[31:38]:   FutureFieldBidSize,
	_FutureFieldName[38:45]:        FutureFieldAskSize,
	_FutureFieldLowerName[38:45]:   FutureFieldAskSize,
	_FutureFieldName[45:50]:        FutureFieldBidID,
	_FutureFieldLowerName[45:50]:   FutureFieldBidID,
	_FutureFieldName[50:55]:        FutureFieldAskID,
	_FutureFieldLowerName[50:55]:   FutureFieldAskID,
	_FutureFieldName[55:66]:        FutureFieldTotalVolume,
	_FutureFieldLowerName[55:66]:   FutureFieldTotalVolume,
	_FutureFieldName[66:74]:        FutureFieldLastSize,
	_FutureFieldLowerName[66:74]:   FutureFieldLastSize,
	_FutureFieldName[74:83]:        FutureFieldQuoteTime,
	_FutureFieldLowerName[74:83]:   FutureFieldQuoteTime,
	_FutureFieldName[83:92]:        FutureFieldTradeTime,
	_FutureFieldLowerName[83:92]:   FutureFieldTradeTime,
	_FutureFieldName[92:101]:       FutureFieldHighPrice,
	_FutureFieldLowerName[92:101]:  FutureFieldHighPrice,
	_FutureFieldName[101:109]:      FutureFieldLowPrice,
	_FutureFieldLowerName[101:109]: FutureFieldLowPrice,
	_FutureFieldName[109:119]:      FutureFieldClosePrice,
	_FutureFieldLowerName[109:119]: FutureFieldClosePrice,
	_FutureFieldName[119:129]:      FutureFieldExchangeID,
	_FutureFieldLowerName[119:129]: FutureFieldExchangeID,
	_FutureFieldName[129:140]:      FutureFieldDescription,
	_FutureFieldLowerName[129:140]: FutureFieldDescription,
	_FutureFieldName[140:146]:      FutureFieldLastID,
	_FutureFieldLowerName[140:146]: FutureFieldLastID,
	_FutureFieldName[146:155]:      FutureFieldOpenPrice,
	_FutureFieldLowerName[146:155]: FutureFieldOpenPrice,
	_FutureFieldName[155:164]:      FutureFieldNetChange,
	_FutureFieldLowerName[155:164]: FutureFieldNetChange,
	_FutureFieldName[164:177]:      FutureFieldPercentChange,
	_FutureFieldLowerName[164:177]: FutureFieldPercentChange,
	_FutureFieldName[177:189]:      FutureFieldExchangeName,
	_FutureFieldLowerName[177:189]: FutureFieldExchangeName,
	_FutureFieldName[189:203]:      FutureFieldSecurityStatus,
	_FutureFieldLowerName[189:203]: FutureFieldSecurityStatus,
	_FutureFieldName[203:215]:      FutureFieldOpenInterest,
	_FutureFieldLowerName[203:215]: FutureFieldOpenInterest,
	_FutureFieldName[215:219]:      FutureFieldMark,
	_FutureFieldLowerName[215:219]: FutureFieldMark,
	_FutureFieldName[219:223]:      FutureFieldTick,
	_FutureFieldLowerName[219:223]: FutureFieldTick,
	_FutureFieldName[223:233]:      FutureFieldTickAmount,
	_FutureFieldLowerName[223:233]: FutureFieldTickAmount,
	_FutureFieldName[233:240]:      FutureFieldProduct,
	_FutureFieldLowerName[233:240]: FutureFieldProduct,
	_FutureFieldName[240:254]:      FutureFieldFuturePriceFmt,
	_FutureFieldLowerName[240:254]: FutureFieldFuturePriceFmt,
	_FutureFieldName[254:266]:      FutureFieldTradingHours,
	_FutureFieldLowerName[254:266]: FutureFieldTradingHours,
	_FutureFieldName[266:276]:      FutureFieldIsTradable,
	_FutureFieldLowerName[266:276]: FutureFieldIsTradable,
	_FutureFieldName[276:286]:      FutureFieldMultiplier,
	_FutureFieldLowerName[276:286]: FutureFieldMultiplier,
	_FutureFieldName[286:294]:      FutureFieldIsActive,
	_FutureFieldLowerName[286:294]: FutureFieldIsActive,
	_FutureFieldName[294:309]:      FutureFieldSettlementPrice,
	_FutureFieldLowerName[294:309]: FutureFieldSettlementPrice,
	_FutureFieldName[309:321]:      FutureFieldActiveSymbol,
	_FutureFieldLowerName[309:321]: FutureFieldActiveSymbol,
	_FutureFieldName[321:335]:      FutureFieldExpirationDate,
	_FutureFieldLowerName[321:335]: FutureFieldExpirationDate,
	_FutureFieldName[335:350]:      FutureFieldExpirationStyle,
	_FutureFieldLowerName[335:350]: FutureFieldExpirationStyle,
	_FutureFieldName[350:357]:      FutureFieldAskTime,
	_FutureFieldLowerName[350:357]: FutureFieldAskTime,
	_FutureFieldName[357:364]:      FutureFieldBidTime,
	_FutureFieldLowerName[357:364]: FutureFieldBidTime,
	_FutureFieldName[364:379]:      FutureFieldQuotedInSession,
	_FutureFieldLowerName[364:379]: FutureFieldQuotedInSession,
	_FutureFieldName[379:393]:      FutureFieldSettlementDate,
	_FutureFieldLowerName[379:393]: FutureFieldSettlementDate,
}

var _FutureFieldNames = []string{
	_FutureFieldName[0:6],
	_FutureFieldName[6:14],
	_FutureFieldName[14:22],
	_FutureFieldName[22:31],
	_FutureFieldName[31:38],
	_FutureFieldName[38:45],
	_FutureFieldName[45:50],
	_FutureFieldName[50:55],
	_FutureFieldName[55:66],
	_FutureFieldName[66:74],
	_FutureFieldName[74:83],
	_FutureFieldName[83:92],
	_FutureFieldName[92:101],
	_FutureFieldName[101:109],
	_FutureFieldName[109:119],
	_FutureFieldName[119:129],
	_FutureFieldName[129:140],
	_FutureFieldName[140:146],
	_FutureFieldName[146:155],
	_FutureFieldName[155:164],
	_FutureFieldName[164:177],
	_FutureFieldName[177:189],
	_FutureFieldName[189:203],
	_FutureFieldName[203:215],
	_FutureFieldName[215:219],
	_FutureFieldName[219:223],
	_FutureFieldName[223:233],
	_FutureFieldName[233:240],
	_FutureFieldName[240:254],
	_FutureFieldName[254:266],
	_FutureFieldName[266:276],
	_FutureFieldName[276:286],
	_FutureFieldName[286:294],
	_FutureFieldName[294:309],
	_FutureFieldName[309:321],
	_FutureFieldName[321:335],
	_FutureFieldName[335:350],
	_FutureFieldName[350:357],
	_FutureFieldName[357:364],
	_FutureFieldName[364:379],
	_FutureFieldName[379:393],
}

// FutureFieldString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FutureFieldString(s string) (FutureField, error) {
	if val, ok := _FutureFieldNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FutureFieldNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FutureField values", s)
}

// FutureFieldValues returns all values of the enum
func FutureFieldValues() []FutureField {
	return _FutureFieldValues
}

// FutureFieldStrings returns a slice of all String values of the enum
func FutureFieldStrings() []string {
	strs := make([]string, len(_FutureFieldNames))
	copy(strs, _FutureFieldNames)
	return strs
}

// IsAFutureField returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FutureField) IsAFutureField() bool {
	for _, v := range _FutureFieldValues {
		if i == v {
			return true
		}
	}
	return false
}
