// Code generated by "enumer -type OptionField -trimprefix OptionField"; DO NOT EDIT.

package td

import (
	"fmt"
	"strings"
)

const _OptionFieldName = "SymbolDescriptionBidPriceAskPriceLastPriceHighPriceLowPriceClosePriceTotalVolumeOpenInterestVolatilityMoneyIntrinsicValueExpirationYearMultiplierDigitsOpenPriceBidSizeAskSizeLastSizeNetChangeStrikePriceContractTypeUnderlyingExpirationMonthDeliverablesTimeValueExpirationDayDaysToExpirationDeltaGammaThetaVegaRhoSecurityStatusTheoreticalOptionValueUnderlyingPriceUVExpirationTypeMarkPriceQuoteTimeTradeTimeExchangeExchangeNameLastTradingDaySettlementTypeNetPercentChangeMarkPriceNetChangeMarkPricePercentChangeImpliedYieldisPennyPilotOptionRoot52WeekHigh52WeekLowIndicativeAskPriceIndicativeBidPriceIndicativeQuoteTimeExerciseType"

var _OptionFieldIndex = [...]uint16{0, 6, 17, 25, 33, 42, 51, 59, 69, 80, 92, 102, 121, 135, 145, 151, 160, 167, 174, 182, 191, 202, 214, 224, 239, 251, 260, 273, 289, 294, 299, 304, 308, 311, 325, 347, 362, 378, 387, 396, 405, 413, 425, 439, 453, 469, 487, 509, 521, 533, 543, 553, 562, 580, 598, 617, 629}

const _OptionFieldLowerName = "symboldescriptionbidpriceaskpricelastpricehighpricelowpriceclosepricetotalvolumeopeninterestvolatilitymoneyintrinsicvalueexpirationyearmultiplierdigitsopenpricebidsizeasksizelastsizenetchangestrikepricecontracttypeunderlyingexpirationmonthdeliverablestimevalueexpirationdaydaystoexpirationdeltagammathetavegarhosecuritystatustheoreticaloptionvalueunderlyingpriceuvexpirationtypemarkpricequotetimetradetimeexchangeexchangenamelasttradingdaysettlementtypenetpercentchangemarkpricenetchangemarkpricepercentchangeimpliedyieldispennypilotoptionroot52weekhigh52weeklowindicativeaskpriceindicativebidpriceindicativequotetimeexercisetype"

func (i OptionField) String() string {
	if i >= OptionField(len(_OptionFieldIndex)-1) {
		return fmt.Sprintf("OptionField(%d)", i)
	}
	return _OptionFieldName[_OptionFieldIndex[i]:_OptionFieldIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OptionFieldNoOp() {
	var x [1]struct{}
	_ = x[OptionFieldSymbol-(0)]
	_ = x[OptionFieldDescription-(1)]
	_ = x[OptionFieldBidPrice-(2)]
	_ = x[OptionFieldAskPrice-(3)]
	_ = x[OptionFieldLastPrice-(4)]
	_ = x[OptionFieldHighPrice-(5)]
	_ = x[OptionFieldLowPrice-(6)]
	_ = x[OptionFieldClosePrice-(7)]
	_ = x[OptionFieldTotalVolume-(8)]
	_ = x[OptionFieldOpenInterest-(9)]
	_ = x[OptionFieldVolatility-(10)]
	_ = x[OptionFieldMoneyIntrinsicValue-(11)]
	_ = x[OptionFieldExpirationYear-(12)]
	_ = x[OptionFieldMultiplier-(13)]
	_ = x[OptionFieldDigits-(14)]
	_ = x[OptionFieldOpenPrice-(15)]
	_ = x[OptionFieldBidSize-(16)]
	_ = x[OptionFieldAskSize-(17)]
	_ = x[OptionFieldLastSize-(18)]
	_ = x[OptionFieldNetChange-(19)]
	_ = x[OptionFieldStrikePrice-(20)]
	_ = x[OptionFieldContractType-(21)]
	_ = x[OptionFieldUnderlying-(22)]
	_ = x[OptionFieldExpirationMonth-(23)]
	_ = x[OptionFieldDeliverables-(24)]
	_ = x[OptionFieldTimeValue-(25)]
	_ = x[OptionFieldExpirationDay-(26)]
	_ = x[OptionFieldDaysToExpiration-(27)]
	_ = x[OptionFieldDelta-(28)]
	_ = x[OptionFieldGamma-(29)]
	_ = x[OptionFieldTheta-(30)]
	_ = x[OptionFieldVega-(31)]
	_ = x[OptionFieldRho-(32)]
	_ = x[OptionFieldSecurityStatus-(33)]
	_ = x[OptionFieldTheoreticalOptionValue-(34)]
	_ = x[OptionFieldUnderlyingPrice-(35)]
	_ = x[OptionFieldUVExpirationType-(36)]
	_ = x[OptionFieldMarkPrice-(37)]
	_ = x[OptionFieldQuoteTime-(38)]
	_ = x[OptionFieldTradeTime-(39)]
	_ = x[OptionFieldExchange-(40)]
	_ = x[OptionFieldExchangeName-(41)]
	_ = x[OptionFieldLastTradingDay-(42)]
	_ = x[OptionFieldSettlementType-(43)]
	_ = x[OptionFieldNetPercentChange-(44)]
	_ = x[OptionFieldMarkPriceNetChange-(45)]
	_ = x[OptionFieldMarkPricePercentChange-(46)]
	_ = x[OptionFieldImpliedYield-(47)]
	_ = x[OptionFieldisPennyPilot-(48)]
	_ = x[OptionFieldOptionRoot-(49)]
	_ = x[OptionField52WeekHigh-(50)]
	_ = x[OptionField52WeekLow-(51)]
	_ = x[OptionFieldIndicativeAskPrice-(52)]
	_ = x[OptionFieldIndicativeBidPrice-(53)]
	_ = x[OptionFieldIndicativeQuoteTime-(54)]
	_ = x[OptionFieldExerciseType-(55)]
}

var _OptionFieldValues = []OptionField{OptionFieldSymbol, OptionFieldDescription, OptionFieldBidPrice, OptionFieldAskPrice, OptionFieldLastPrice, OptionFieldHighPrice, OptionFieldLowPrice, OptionFieldClosePrice, OptionFieldTotalVolume, OptionFieldOpenInterest, OptionFieldVolatility, OptionFieldMoneyIntrinsicValue, OptionFieldExpirationYear, OptionFieldMultiplier, OptionFieldDigits, OptionFieldOpenPrice, OptionFieldBidSize, OptionFieldAskSize, OptionFieldLastSize, OptionFieldNetChange, OptionFieldStrikePrice, OptionFieldContractType, OptionFieldUnderlying, OptionFieldExpirationMonth, OptionFieldDeliverables, OptionFieldTimeValue, OptionFieldExpirationDay, OptionFieldDaysToExpiration, OptionFieldDelta, OptionFieldGamma, OptionFieldTheta, OptionFieldVega, OptionFieldRho, OptionFieldSecurityStatus, OptionFieldTheoreticalOptionValue, OptionFieldUnderlyingPrice, OptionFieldUVExpirationType, OptionFieldMarkPrice, OptionFieldQuoteTime, OptionFieldTradeTime, OptionFieldExchange, OptionFieldExchangeName, OptionFieldLastTradingDay, OptionFieldSettlementType, OptionFieldNetPercentChange, OptionFieldMarkPriceNetChange, OptionFieldMarkPricePercentChange, OptionFieldImpliedYield, OptionFieldisPennyPilot, OptionFieldOptionRoot, OptionField52WeekHigh, OptionField52WeekLow, OptionFieldIndicativeAskPrice, OptionFieldIndicativeBidPrice, OptionFieldIndicativeQuoteTime, OptionFieldExerciseType}

var _OptionFieldNameToValueMap = map[string]OptionField{
	_OptionFieldName[0:6]:          OptionFieldSymbol,
	_OptionFieldLowerName[0:6]:     OptionFieldSymbol,
	_OptionFieldName[6:17]:         OptionFieldDescription,
	_OptionFieldLowerName[6:17]:    OptionFieldDescription,
	_OptionFieldName[17:25]:        OptionFieldBidPrice,
	_OptionFieldLowerName[17:25]:   OptionFieldBidPrice,
	_OptionFieldName[25:33]:        OptionFieldAskPrice,
	_OptionFieldLowerName[25:33]:   OptionFieldAskPrice,
	_OptionFieldName[33:42]:        OptionFieldLastPrice,
	_OptionFieldLowerName[33:42]:   OptionFieldLastPrice,
	_OptionFieldName[42:51]:        OptionFieldHighPrice,
	_OptionFieldLowerName[42:51]:   OptionFieldHighPrice,
	_OptionFieldName[51:59]:        OptionFieldLowPrice,
	_OptionFieldLowerName[51:59]:   OptionFieldLowPrice,
	_OptionFieldName[59:69]:        OptionFieldClosePrice,
	_OptionFieldLowerName[59:69]:   OptionFieldClosePrice,
	_OptionFieldName[69:80]:        OptionFieldTotalVolume,
	_OptionFieldLowerName[69:80]:   OptionFieldTotalVolume,
	_OptionFieldName[80:92]:        OptionFieldOpenInterest,
	_OptionFieldLowerName[80:92]:   OptionFieldOpenInterest,
	_OptionFieldName[92:102]:       OptionFieldVolatility,
	_OptionFieldLowerName[92:102]:  OptionFieldVolatility,
	_OptionFieldName[102:121]:      OptionFieldMoneyIntrinsicValue,
	_OptionFieldLowerName[102:121]: OptionFieldMoneyIntrinsicValue,
	_OptionFieldName[121:135]:      OptionFieldExpirationYear,
	_OptionFieldLowerName[121:135]: OptionFieldExpirationYear,
	_OptionFieldName[135:145]:      OptionFieldMultiplier,
	_OptionFieldLowerName[135:145]: OptionFieldMultiplier,
	_OptionFieldName[145:151]:      OptionFieldDigits,
	_OptionFieldLowerName[145:151]: OptionFieldDigits,
	_OptionFieldName[151:160]:      OptionFieldOpenPrice,
	_OptionFieldLowerName[151:160]: OptionFieldOpenPrice,
	_OptionFieldName[160:167]:      OptionFieldBidSize,
	_OptionFieldLowerName[160:167]: OptionFieldBidSize,
	_OptionFieldName[167:174]:      OptionFieldAskSize,
	_OptionFieldLowerName[167:174]: OptionFieldAskSize,
	_OptionFieldName[174:182]:      OptionFieldLastSize,
	_OptionFieldLowerName[174:182]: OptionFieldLastSize,
	_OptionFieldName[182:191]:      OptionFieldNetChange,
	_OptionFieldLowerName[182:191]: OptionFieldNetChange,
	_OptionFieldName[191:202]:      OptionFieldStrikePrice,
	_OptionFieldLowerName[191:202]: OptionFieldStrikePrice,
	_OptionFieldName[202:214]:      OptionFieldContractType,
	_OptionFieldLowerName[202:214]: OptionFieldContractType,
	_OptionFieldName[214:224]:      OptionFieldUnderlying,
	_OptionFieldLowerName[214:224]: OptionFieldUnderlying,
	_OptionFieldName[224:239]:      OptionFieldExpirationMonth,
	_OptionFieldLowerName[224:239]: OptionFieldExpirationMonth,
	_OptionFieldName[239:251]:      OptionFieldDeliverables,
	_OptionFieldLowerName[239:251]: OptionFieldDeliverables,
	_OptionFieldName[251:260]:      OptionFieldTimeValue,
	_OptionFieldLowerName[251:260]: OptionFieldTimeValue,
	_OptionFieldName[260:273]:      OptionFieldExpirationDay,
	_OptionFieldLowerName[260:273]: OptionFieldExpirationDay,
	_OptionFieldName[273:289]:      OptionFieldDaysToExpiration,
	_OptionFieldLowerName[273:289]: OptionFieldDaysToExpiration,
	_OptionFieldName[289:294]:      OptionFieldDelta,
	_OptionFieldLowerName[289:294]: OptionFieldDelta,
	_OptionFieldName[294:299]:      OptionFieldGamma,
	_OptionFieldLowerName[294:299]: OptionFieldGamma,
	_OptionFieldName[299:304]:      OptionFieldTheta,
	_OptionFieldLowerName[299:304]: OptionFieldTheta,
	_OptionFieldName[304:308]:      OptionFieldVega,
	_OptionFieldLowerName[304:308]: OptionFieldVega,
	_OptionFieldName[308:311]:      OptionFieldRho,
	_OptionFieldLowerName[308:311]: OptionFieldRho,
	_OptionFieldName[311:325]:      OptionFieldSecurityStatus,
	_OptionFieldLowerName[311:325]: OptionFieldSecurityStatus,
	_OptionFieldName[325:347]:      OptionFieldTheoreticalOptionValue,
	_OptionFieldLowerName[325:347]: OptionFieldTheoreticalOptionValue,
	_OptionFieldName[347:362]:      OptionFieldUnderlyingPrice,
	_OptionFieldLowerName[347:362]: OptionFieldUnderlyingPrice,
	_OptionFieldName[362:378]:      OptionFieldUVExpirationType,
	_OptionFieldLowerName[362:378]: OptionFieldUVExpirationType,
	_OptionFieldName[378:387]:      OptionFieldMarkPrice,
	_OptionFieldLowerName[378:387]: OptionFieldMarkPrice,
	_OptionFieldName[387:396]:      OptionFieldQuoteTime,
	_OptionFieldLowerName[387:396]: OptionFieldQuoteTime,
	_OptionFieldName[396:405]:      OptionFieldTradeTime,
	_OptionFieldLowerName[396:405]: OptionFieldTradeTime,
	_OptionFieldName[405:413]:      OptionFieldExchange,
	_OptionFieldLowerName[405:413]: OptionFieldExchange,
	_OptionFieldName[413:425]:      OptionFieldExchangeName,
	_OptionFieldLowerName[413:425]: OptionFieldExchangeName,
	_OptionFieldName[425:439]:      OptionFieldLastTradingDay,
	_OptionFieldLowerName[425:439]: OptionFieldLastTradingDay,
	_OptionFieldName[439:453]:      OptionFieldSettlementType,
	_OptionFieldLowerName[439:453]: OptionFieldSettlementType,
	_OptionFieldName[453:469]:      OptionFieldNetPercentChange,
	_OptionFieldLowerName[453:469]: OptionFieldNetPercentChange,
	_OptionFieldName[469:487]:      OptionFieldMarkPriceNetChange,
	_OptionFieldLowerName[469:487]: OptionFieldMarkPriceNetChange,
	_OptionFieldName[487:509]:      OptionFieldMarkPricePercentChange,
	_OptionFieldLowerName[487:509]: OptionFieldMarkPricePercentChange,
	_OptionFieldName[509:521]:      OptionFieldImpliedYield,
	_OptionFieldLowerName[509:521]: OptionFieldImpliedYield,
	_OptionFieldName[521:533]:      OptionFieldisPennyPilot,
	_OptionFieldLowerName[521:533]: OptionFieldisPennyPilot,
	_OptionFieldName[533:543]:      OptionFieldOptionRoot,
	_OptionFieldLowerName[533:543]: OptionFieldOptionRoot,
	_OptionFieldName[543:553]:      OptionField52WeekHigh,
	_OptionFieldLowerName[543:553]: OptionField52WeekHigh,
	_OptionFieldName[553:562]:      OptionField52WeekLow,
	_OptionFieldLowerName[553:562]: OptionField52WeekLow,
	_OptionFieldName[562:580]:      OptionFieldIndicativeAskPrice,
	_OptionFieldLowerName[562:580]: OptionFieldIndicativeAskPrice,
	_OptionFieldName[580:598]:      OptionFieldIndicativeBidPrice,
	_OptionFieldLowerName[580:598]: OptionFieldIndicativeBidPrice,
	_OptionFieldName[598:617]:      OptionFieldIndicativeQuoteTime,
	_OptionFieldLowerName[598:617]: OptionFieldIndicativeQuoteTime,
	_OptionFieldName[617:629]:      OptionFieldExerciseType,
	_OptionFieldLowerName[617:629]: OptionFieldExerciseType,
}

var _OptionFieldNames = []string{
	_OptionFieldName[0:6],
	_OptionFieldName[6:17],
	_OptionFieldName[17:25],
	_OptionFieldName[25:33],
	_OptionFieldName[33:42],
	_OptionFieldName[42:51],
	_OptionFieldName[51:59],
	_OptionFieldName[59:69],
	_OptionFieldName[69:80],
	_OptionFieldName[80:92],
	_OptionFieldName[92:102],
	_OptionFieldName[102:121],
	_OptionFieldName[121:135],
	_OptionFieldName[135:145],
	_OptionFieldName[145:151],
	_OptionFieldName[151:160],
	_OptionFieldName[160:167],
	_OptionFieldName[167:174],
	_OptionFieldName[174:182],
	_OptionFieldName[182:191],
	_OptionFieldName[191:202],
	_OptionFieldName[202:214],
	_OptionFieldName[214:224],
	_OptionFieldName[224:239],
	_OptionFieldName[239:251],
	_OptionFieldName[251:260],
	_OptionFieldName[260:273],
	_OptionFieldName[273:289],
	_OptionFieldName[289:294],
	_OptionFieldName[294:299],
	_OptionFieldName[299:304],
	_OptionFieldName[304:308],
	_OptionFieldName[308:311],
	_OptionFieldName[311:325],
	_OptionFieldName[325:347],
	_OptionFieldName[347:362],
	_OptionFieldName[362:378],
	_OptionFieldName[378:387],
	_OptionFieldName[387:396],
	_OptionFieldName[396:405],
	_OptionFieldName[405:413],
	_OptionFieldName[413:425],
	_OptionFieldName[425:439],
	_OptionFieldName[439:453],
	_OptionFieldName[453:469],
	_OptionFieldName[469:487],
	_OptionFieldName[487:509],
	_OptionFieldName[509:521],
	_OptionFieldName[521:533],
	_OptionFieldName[533:543],
	_OptionFieldName[543:553],
	_OptionFieldName[553:562],
	_OptionFieldName[562:580],
	_OptionFieldName[580:598],
	_OptionFieldName[598:617],
	_OptionFieldName[617:629],
}

// OptionFieldString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OptionFieldString(s string) (OptionField, error) {
	if val, ok := _OptionFieldNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OptionFieldNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OptionField values", s)
}

// OptionFieldValues returns all values of the enum
func OptionFieldValues() []OptionField {
	return _OptionFieldValues
}

// OptionFieldStrings returns a slice of all String values of the enum
func OptionFieldStrings() []string {
	strs := make([]string, len(_OptionFieldNames))
	copy(strs, _OptionFieldNames)
	return strs
}

// IsAOptionField returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OptionField) IsAOptionField() bool {
	for _, v := range _OptionFieldValues {
		if i == v {
			return true
		}
	}
	return false
}
