// Code generated by "enumer -type PeriodType -json -trimprefix PeriodType -transform lower"; DO NOT EDIT.

package td

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PeriodTypeName = "unspecifieddaymonthyearytd"

var _PeriodTypeIndex = [...]uint8{0, 11, 14, 19, 23, 26}

const _PeriodTypeLowerName = "unspecifieddaymonthyearytd"

func (i PeriodType) String() string {
	if i >= PeriodType(len(_PeriodTypeIndex)-1) {
		return fmt.Sprintf("PeriodType(%d)", i)
	}
	return _PeriodTypeName[_PeriodTypeIndex[i]:_PeriodTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PeriodTypeNoOp() {
	var x [1]struct{}
	_ = x[PeriodTypeUnspecified-(0)]
	_ = x[PeriodTypeDay-(1)]
	_ = x[PeriodTypeMonth-(2)]
	_ = x[PeriodTypeYear-(3)]
	_ = x[PeriodTypeYTD-(4)]
}

var _PeriodTypeValues = []PeriodType{PeriodTypeUnspecified, PeriodTypeDay, PeriodTypeMonth, PeriodTypeYear, PeriodTypeYTD}

var _PeriodTypeNameToValueMap = map[string]PeriodType{
	_PeriodTypeName[0:11]:       PeriodTypeUnspecified,
	_PeriodTypeLowerName[0:11]:  PeriodTypeUnspecified,
	_PeriodTypeName[11:14]:      PeriodTypeDay,
	_PeriodTypeLowerName[11:14]: PeriodTypeDay,
	_PeriodTypeName[14:19]:      PeriodTypeMonth,
	_PeriodTypeLowerName[14:19]: PeriodTypeMonth,
	_PeriodTypeName[19:23]:      PeriodTypeYear,
	_PeriodTypeLowerName[19:23]: PeriodTypeYear,
	_PeriodTypeName[23:26]:      PeriodTypeYTD,
	_PeriodTypeLowerName[23:26]: PeriodTypeYTD,
}

var _PeriodTypeNames = []string{
	_PeriodTypeName[0:11],
	_PeriodTypeName[11:14],
	_PeriodTypeName[14:19],
	_PeriodTypeName[19:23],
	_PeriodTypeName[23:26],
}

// PeriodTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PeriodTypeString(s string) (PeriodType, error) {
	if val, ok := _PeriodTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PeriodTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PeriodType values", s)
}

// PeriodTypeValues returns all values of the enum
func PeriodTypeValues() []PeriodType {
	return _PeriodTypeValues
}

// PeriodTypeStrings returns a slice of all String values of the enum
func PeriodTypeStrings() []string {
	strs := make([]string, len(_PeriodTypeNames))
	copy(strs, _PeriodTypeNames)
	return strs
}

// IsAPeriodType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PeriodType) IsAPeriodType() bool {
	for _, v := range _PeriodTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PeriodType
func (i PeriodType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PeriodType
func (i *PeriodType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PeriodType should be a string, got %s", data)
	}

	var err error
	*i, err = PeriodTypeString(s)
	return err
}
