// Code generated by "enumer -type service -json -trimprefix service -transform snaker-upper"; DO NOT EDIT.

package td

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _serviceName = "UnspecifiedAdminLeveloneEquitiesLeveloneOptionsLeveloneFuturesLeveloneFuturesOptionsLeveloneForexNyseBookNasdaqBookOptionsBookChartEquityChartFuturesScreenerEquityScreenerOptionAcctActivity"

var _serviceIndex = [...]uint8{0, 11, 16, 32, 47, 62, 84, 97, 105, 115, 126, 137, 149, 163, 177, 189}

const _serviceLowerName = "unspecifiedadminleveloneequitiesleveloneoptionslevelonefutureslevelonefuturesoptionsleveloneforexnysebooknasdaqbookoptionsbookchartequitychartfuturesscreenerequityscreeneroptionacctactivity"

func (i service) String() string {
	if i >= service(len(_serviceIndex)-1) {
		return fmt.Sprintf("service(%d)", i)
	}
	return _serviceName[_serviceIndex[i]:_serviceIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _serviceNoOp() {
	var x [1]struct{}
	_ = x[serviceUnspecified-(0)]
	_ = x[serviceAdmin-(1)]
	_ = x[serviceLeveloneEquities-(2)]
	_ = x[serviceLeveloneOptions-(3)]
	_ = x[serviceLeveloneFutures-(4)]
	_ = x[serviceLeveloneFuturesOptions-(5)]
	_ = x[serviceLeveloneForex-(6)]
	_ = x[serviceNyseBook-(7)]
	_ = x[serviceNasdaqBook-(8)]
	_ = x[serviceOptionsBook-(9)]
	_ = x[serviceChartEquity-(10)]
	_ = x[serviceChartFutures-(11)]
	_ = x[serviceScreenerEquity-(12)]
	_ = x[serviceScreenerOption-(13)]
	_ = x[serviceAcctActivity-(14)]
}

var _serviceValues = []service{serviceUnspecified, serviceAdmin, serviceLeveloneEquities, serviceLeveloneOptions, serviceLeveloneFutures, serviceLeveloneFuturesOptions, serviceLeveloneForex, serviceNyseBook, serviceNasdaqBook, serviceOptionsBook, serviceChartEquity, serviceChartFutures, serviceScreenerEquity, serviceScreenerOption, serviceAcctActivity}

var _serviceNameToValueMap = map[string]service{
	_serviceName[0:11]:         serviceUnspecified,
	_serviceLowerName[0:11]:    serviceUnspecified,
	_serviceName[11:16]:        serviceAdmin,
	_serviceLowerName[11:16]:   serviceAdmin,
	_serviceName[16:32]:        serviceLeveloneEquities,
	_serviceLowerName[16:32]:   serviceLeveloneEquities,
	_serviceName[32:47]:        serviceLeveloneOptions,
	_serviceLowerName[32:47]:   serviceLeveloneOptions,
	_serviceName[47:62]:        serviceLeveloneFutures,
	_serviceLowerName[47:62]:   serviceLeveloneFutures,
	_serviceName[62:84]:        serviceLeveloneFuturesOptions,
	_serviceLowerName[62:84]:   serviceLeveloneFuturesOptions,
	_serviceName[84:97]:        serviceLeveloneForex,
	_serviceLowerName[84:97]:   serviceLeveloneForex,
	_serviceName[97:105]:       serviceNyseBook,
	_serviceLowerName[97:105]:  serviceNyseBook,
	_serviceName[105:115]:      serviceNasdaqBook,
	_serviceLowerName[105:115]: serviceNasdaqBook,
	_serviceName[115:126]:      serviceOptionsBook,
	_serviceLowerName[115:126]: serviceOptionsBook,
	_serviceName[126:137]:      serviceChartEquity,
	_serviceLowerName[126:137]: serviceChartEquity,
	_serviceName[137:149]:      serviceChartFutures,
	_serviceLowerName[137:149]: serviceChartFutures,
	_serviceName[149:163]:      serviceScreenerEquity,
	_serviceLowerName[149:163]: serviceScreenerEquity,
	_serviceName[163:177]:      serviceScreenerOption,
	_serviceLowerName[163:177]: serviceScreenerOption,
	_serviceName[177:189]:      serviceAcctActivity,
	_serviceLowerName[177:189]: serviceAcctActivity,
}

var _serviceNames = []string{
	_serviceName[0:11],
	_serviceName[11:16],
	_serviceName[16:32],
	_serviceName[32:47],
	_serviceName[47:62],
	_serviceName[62:84],
	_serviceName[84:97],
	_serviceName[97:105],
	_serviceName[105:115],
	_serviceName[115:126],
	_serviceName[126:137],
	_serviceName[137:149],
	_serviceName[149:163],
	_serviceName[163:177],
	_serviceName[177:189],
}

// serviceString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func serviceString(s string) (service, error) {
	if val, ok := _serviceNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _serviceNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to service values", s)
}

// serviceValues returns all values of the enum
func serviceValues() []service {
	return _serviceValues
}

// serviceStrings returns a slice of all String values of the enum
func serviceStrings() []string {
	strs := make([]string, len(_serviceNames))
	copy(strs, _serviceNames)
	return strs
}

// IsAservice returns "true" if the value is listed in the enum definition. "false" otherwise
func (i service) IsAservice() bool {
	for _, v := range _serviceValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for service
func (i service) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for service
func (i *service) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("service should be a string, got %s", data)
	}

	var err error
	*i, err = serviceString(s)
	return err
}
