// Code generated by "enumer -type Sort -json -trimprefix Sort -transform snake-upper"; DO NOT EDIT.

package td

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SortName = "UNSPECIFIEDVOLUMETRADESPERCENT_CHANGE_UPPERCENT_CHANGE_DOWN"

var _SortIndex = [...]uint8{0, 11, 17, 23, 40, 59}

const _SortLowerName = "unspecifiedvolumetradespercent_change_uppercent_change_down"

func (i Sort) String() string {
	if i >= Sort(len(_SortIndex)-1) {
		return fmt.Sprintf("Sort(%d)", i)
	}
	return _SortName[_SortIndex[i]:_SortIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SortNoOp() {
	var x [1]struct{}
	_ = x[SortUnspecified-(0)]
	_ = x[SortVolume-(1)]
	_ = x[SortTrades-(2)]
	_ = x[SortPercentChangeUp-(3)]
	_ = x[SortPercentChangeDown-(4)]
}

var _SortValues = []Sort{SortUnspecified, SortVolume, SortTrades, SortPercentChangeUp, SortPercentChangeDown}

var _SortNameToValueMap = map[string]Sort{
	_SortName[0:11]:  SortUnspecified,
	_SortName[11:17]: SortVolume,
	_SortName[17:23]: SortTrades,
	_SortName[23:40]: SortPercentChangeUp,
	_SortName[40:59]: SortPercentChangeDown,
}

var _SortLowerNameToValueMap = map[string]Sort{
	_SortLowerName[0:11]:  SortUnspecified,
	_SortLowerName[11:17]: SortVolume,
	_SortLowerName[17:23]: SortTrades,
	_SortLowerName[23:40]: SortPercentChangeUp,
	_SortLowerName[40:59]: SortPercentChangeDown,
}

var _SortNames = []string{
	_SortName[0:11],
	_SortName[11:17],
	_SortName[17:23],
	_SortName[23:40],
	_SortName[40:59],
}

// SortString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SortString(s string) (Sort, error) {
	if val, ok := _SortNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SortLowerNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Sort values", s)
}

// SortValues returns all values of the enum
func SortValues() []Sort {
	return _SortValues
}

// SortStrings returns a slice of all String values of the enum
func SortStrings() []string {
	strs := make([]string, len(_SortNames))
	copy(strs, _SortNames)
	return strs
}

// IsASort returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Sort) IsASort() bool {
	for _, v := range _SortValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Sort
func (i Sort) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Sort
func (i *Sort) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Sort should be a string, got %s", data)
	}

	var err error
	*i, err = SortString(s)
	return err
}
