// Code generated by "enumer -type SymbolID -json -trimprefix SymbolID -linecomment"; DO NOT EDIT.

package td

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SymbolIDName = "Unspecified$DJI$COMPX$SPXNYSENASDAQOTCBBINDEX_ALLEQUITY_ALLOPTION_ALLOPTION_PUTOPTION_CALL"

var _SymbolIDIndex = [...]uint8{0, 11, 15, 21, 25, 29, 35, 40, 49, 59, 69, 79, 90}

const _SymbolIDLowerName = "unspecified$dji$compx$spxnysenasdaqotcbbindex_allequity_alloption_alloption_putoption_call"

func (i SymbolID) String() string {
	if i >= SymbolID(len(_SymbolIDIndex)-1) {
		return fmt.Sprintf("SymbolID(%d)", i)
	}
	return _SymbolIDName[_SymbolIDIndex[i]:_SymbolIDIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SymbolIDNoOp() {
	var x [1]struct{}
	_ = x[SymbolIDUnspecified-(0)]
	_ = x[SymbolIDDJI-(1)]
	_ = x[SymbolIDCOMPX-(2)]
	_ = x[SymbolIDSPX-(3)]
	_ = x[SymbolIDNYSE-(4)]
	_ = x[SymbolIDNASDAQ-(5)]
	_ = x[SymbolIDOTCBB-(6)]
	_ = x[SymbolIDIndexAll-(7)]
	_ = x[SymbolIDEquityAll-(8)]
	_ = x[SymbolIDOptionAll-(9)]
	_ = x[SymbolIDOptionPut-(10)]
	_ = x[SymbolIDOptionCall-(11)]
}

var _SymbolIDValues = []SymbolID{SymbolIDUnspecified, SymbolIDDJI, SymbolIDCOMPX, SymbolIDSPX, SymbolIDNYSE, SymbolIDNASDAQ, SymbolIDOTCBB, SymbolIDIndexAll, SymbolIDEquityAll, SymbolIDOptionAll, SymbolIDOptionPut, SymbolIDOptionCall}

var _SymbolIDNameToValueMap = map[string]SymbolID{
	_SymbolIDName[0:11]:  SymbolIDUnspecified,
	_SymbolIDName[11:15]: SymbolIDDJI,
	_SymbolIDName[15:21]: SymbolIDCOMPX,
	_SymbolIDName[21:25]: SymbolIDSPX,
	_SymbolIDName[25:29]: SymbolIDNYSE,
	_SymbolIDName[29:35]: SymbolIDNASDAQ,
	_SymbolIDName[35:40]: SymbolIDOTCBB,
	_SymbolIDName[40:49]: SymbolIDIndexAll,
	_SymbolIDName[49:59]: SymbolIDEquityAll,
	_SymbolIDName[59:69]: SymbolIDOptionAll,
	_SymbolIDName[69:79]: SymbolIDOptionPut,
	_SymbolIDName[79:90]: SymbolIDOptionCall,
}

var _SymbolIDLowerNameToValueMap = map[string]SymbolID{
	_SymbolIDLowerName[0:11]:  SymbolIDUnspecified,
	_SymbolIDLowerName[11:15]: SymbolIDDJI,
	_SymbolIDLowerName[15:21]: SymbolIDCOMPX,
	_SymbolIDLowerName[21:25]: SymbolIDSPX,
	_SymbolIDLowerName[25:29]: SymbolIDNYSE,
	_SymbolIDLowerName[29:35]: SymbolIDNASDAQ,
	_SymbolIDLowerName[35:40]: SymbolIDOTCBB,
	_SymbolIDLowerName[40:49]: SymbolIDIndexAll,
	_SymbolIDLowerName[49:59]: SymbolIDEquityAll,
	_SymbolIDLowerName[59:69]: SymbolIDOptionAll,
	_SymbolIDLowerName[69:79]: SymbolIDOptionPut,
	_SymbolIDLowerName[79:90]: SymbolIDOptionCall,
}

var _SymbolIDNames = []string{
	_SymbolIDName[0:11],
	_SymbolIDName[11:15],
	_SymbolIDName[15:21],
	_SymbolIDName[21:25],
	_SymbolIDName[25:29],
	_SymbolIDName[29:35],
	_SymbolIDName[35:40],
	_SymbolIDName[40:49],
	_SymbolIDName[49:59],
	_SymbolIDName[59:69],
	_SymbolIDName[69:79],
	_SymbolIDName[79:90],
}

// SymbolIDString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SymbolIDString(s string) (SymbolID, error) {
	if val, ok := _SymbolIDNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SymbolIDLowerNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SymbolID values", s)
}

// SymbolIDValues returns all values of the enum
func SymbolIDValues() []SymbolID {
	return _SymbolIDValues
}

// SymbolIDStrings returns a slice of all String values of the enum
func SymbolIDStrings() []string {
	strs := make([]string, len(_SymbolIDNames))
	copy(strs, _SymbolIDNames)
	return strs
}

// IsASymbolID returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SymbolID) IsASymbolID() bool {
	for _, v := range _SymbolIDValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SymbolID
func (i SymbolID) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SymbolID
func (i *SymbolID) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SymbolID should be a string, got %s", data)
	}

	var err error
	*i, err = SymbolIDString(s)
	return err
}
